export const GOOGLE_ADDRESS_TAGS = [
  { id: "route", label: "Street Name (Route)" },
  { id: "street_number", label: "Street Number" },
  { id: "premise", label: "Building/House Name (Premise)" },
  { id: "subpremise", label: "Apartment/Suite (Subpremise)" },
  { id: "neighborhood", label: "Neighborhood" },
  { id: "sublocality", label: "Sublocality (General)" },
  { id: "sublocality_level_1", label: "Sublocality 1 (Village/Ward)" },
  { id: "sublocality_level_2", label: "Sublocality 2" },
  { id: "sublocality_level_3", label: "Sublocality 3 (Chome)" },
  { id: "sublocality_level_4", label: "Sublocality 4 (Block)" },
  { id: "locality", label: "Locality (City)" },
  { id: "postal_town", label: "Postal Town" },
  { id: "administrative_area_level_1", label: "Admin Area 1 (State/Province)" },
  { id: "administrative_area_level_2", label: "Admin Area 2 (County)" },
  { id: "administrative_area_level_3", label: "Admin Area 3 (Province)" },
  { id: "administrative_area_level_4", label: "Admin Area 4 (District)" },
  { id: "administrative_area_level_5", label: "Admin Area 5 (Ward)" },

  { id: "postal_code", label: "Postal Code" },
  { id: "country", label: "Country" },
];

export const ISO_COUNTRIES = [
  { value: "AF", label: "Afghanistan" },
  { value: "AL", label: "Albania" },
  { value: "DZ", label: "Algeria" },
  { value: "AR", label: "Argentina" },
  { value: "AU", label: "Australia" },
  { value: "AT", label: "Austria" },
  { value: "BD", label: "Bangladesh" },
  { value: "BE", label: "Belgium" },
  { value: "BR", label: "Brazil" },
  { value: "CA", label: "Canada" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "China" },
  { value: "CO", label: "Colombia" },
  { value: "CZ", label: "Czechia" },
  { value: "DK", label: "Denmark" },
  { value: "EG", label: "Egypt" },
  { value: "FI", label: "Finland" },
  { value: "FR", label: "France" },
  { value: "DE", label: "Germany" },
  { value: "GR", label: "Greece" },
  { value: "HK", label: "Hong Kong" },
  { value: "HU", label: "Hungary" },
  { value: "IS", label: "Iceland" },
  { value: "IN", label: "India" },
  { value: "ID", label: "Indonesia" },
  { value: "IR", label: "Iran" },
  { value: "IQ", label: "Iraq" },
  { value: "IE", label: "Ireland" },
  { value: "IL", label: "Israel" },
  { value: "IT", label: "Italy" },
  { value: "JP", label: "Japan" },
  { value: "KR", label: "South Korea" },
  { value: "MY", label: "Malaysia" },
  { value: "MX", label: "Mexico" },
  { value: "NL", label: "Netherlands" },
  { value: "NZ", label: "New Zealand" },
  { value: "NG", label: "Nigeria" },
  { value: "NO", label: "Norway" },
  { value: "PK", label: "Pakistan" },
  { value: "PH", label: "Philippines" },
  { value: "PL", label: "Poland" },
  { value: "PT", label: "Portugal" },
  { value: "QA", label: "Qatar" },
  { value: "RO", label: "Romania" },
  { value: "RU", label: "Russia" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "SG", label: "Singapore" },
  { value: "ZA", label: "South Africa" },
  { value: "ES", label: "Spain" },
  { value: "SE", label: "Sweden" },
  { value: "CH", label: "Switzerland" },
  { value: "TW", label: "Taiwan" },
  { value: "TH", label: "Thailand" },
  { value: "TR", label: "Turkey" },
  { value: "UA", label: "Ukraine" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "GB", label: "United Kingdom" },
  { value: "US", label: "United States" },
  { value: "VN", label: "Vietnam" },
];
